### ISSUE TITLE
CodeListener not listening....

### ISSUE THREAD

**Issue by leceta** [ccc159/RhinoPythonForVscode#1]
When executing CodeListener command at Rhino no "VS Code Listener Started...." feedback.
 
VS code says "Cannot connect Rhino. Please make sure Rhino is running CodeListener"

VScode Version 1.24.0
CodeListener:  0.1.4
Rhino6: 6.5.18149.14421, 5/29/2018

**Comment by ccc159** [comment]
@leceta Rhino6 is currently not supported. Since our office uses only Rhino5 right now.

It will be supported in the future..

**Comment by ccc159** [comment]
It is supported in the new version.
